README.md
`ShopTalkShow` => `Shop Talk Show`
=> Write `Shop Talk Show` correctly

README.md
Materialize - A modern responsive front-end framework based on Material Design.
=> Add Materialize to Frameworks

README.md
All entries in all lists are now alphabetically ordered as per Contribution Guidelines.
=> Fix entries sorting

README.md
Any entry that contains description is now ending with a full stop/period as per Contribution Guidelines.
=> Fix entries punctuation

README.md
Fixed the list order. It goes G→L→M→P→S→Y.
Accidentally deleted #31.
=> Add Myth (preprocessor)

README.md
Adds OpenType features—ligatures, kerning, and more—to Normalize.css.
=> Add Normalize-OpenType to "Reset and Normalize"

README.md
As per https://github.com/sotayamashita/awesome-css/issues/34 I have added my unstyle.css project to the list.
In addition I have updated unstyle.css and prepped the README.md with instructions and clarity as to what it is about.
=> Add unstyle.css

README.md
Adding my CSS styleguide as 80+ think it's awesome  :sunglasses:
https://github.com/grvcoelho/css
=> Add grvcoelho's css styleguide

README.md
=> Fixed broken link to CSS Structure section

README.md
Adds Single Div Project to list
=> Adds Single Div Project to list

README.md
Been using Aphrodite in my new project for the past 3 weeks, thought it would be wonderful if we can include this source. Meanwhile, both react-with-styles and jss are discovered recently and deemed to be useful as well.
=> Added new CSS in JS src

README.md
Fixed links in **Contents** section
=> Fix "Contents" section

README.md
Minor fix to README.md for consistency.
=> Adds 'back to top' to Miscellaneous section

README.md
This patch adds the [Can I use](http://caniuse.com/) browser support tables. It might be useful for having it listed here as well.
Thank you for considering merging it.
=> Add Can I use - caniuse.com browser support tables

README.md
=> added tutorial section with 2 interactive tuts

README.md
I believe this qualifies with at least the following 2 criteria specified in CONTRIBUTING.md:
(c) absolutely unique in its approach and function
(d) a niche product that fills a gap
Based on the reviews from users of its Chrome extension (https://chrome.google.com/webstore/detail/ifhikkcafabcgolfjegfcgloomalapol), it may satisfy criteria (a) and (b) as well :-)
=> Added Live editor for CSS and LESS (Magic CSS extension for various browsers)

README.md
I was looking at this list, and realized it didn't include a fairly new framework, [Wing](http://usewing.ml).
=> Add Wing (CSS Framework)

README.md
I know sending PRs for adding your own project is something that is frowned upon as mentioned in the guidelines. 
But i want you to give this a consideration, its very simple but unique framework.
Got 1.5k stars on github and is being used by a lot of developers.
It was also on the top of github trending list for a week or so. 
So, check it out if you like it or it satisfies your criteria or not.
=> Added pills.

README.md
Added Milligram minimalist CSS framework.
=> Add Milligram CSS framework.

README.md
* Add Syntax to Podcasts section
* Add Rachel Andrew to Twitter section
=> Add Syntax and Rachel Andrew

README.md
* Removal of Aigis from Style Guide Generators
* This project is no longer maintained [Aigis - CSS Styleguide Generator](https://github.com/aigis-styleguide/aigis)
=> Aigis removal

README.md
updating a moved link.
minor corrections.
=> updating link

README.md
Tasks Done:
- Indented Button for
- Podcasts
- Twitter
- Fixed Button for
- Preprocessors
- Frameworks
- Toolkit
- CSS Structure
=> Fixed various instances of 'Back to Top' Button

README.md
- Added Books
- CSS Secrets
- CSS3: The Missing Manual
- Added Emoji:
- Tutorials
#115
=> Added Separate Section for Books

README.md
Corrections in the details div.
=> Correction in details

README.md
It adds a css grid tutorial from Mozilla to Tutorials section.
=> Added CSS GRID PLAYGROUND Tutorial

README.md
Added Work With Animations to tutorials.
=> Work With Animations

README.md
Adds Tacit CSS framework to list of frameworks.
Yes. It's a "a niche product that fills a gap", mainly pointed at developers with zero skills in terms of CSS or graphic design.
=> Add Tacit CSS Framework

README.md
Add more up-to-date CSS in JS
Yes, I do
=> Add more up-to-date CSS in JS

README.md
A Twitter link removed it was showing Error 404 page.
Was causing builds to fail.
Yes
=> Removed link https://twitter.com/thierrykoblentz

README.md
Fixes the link to table on contents within the readme
Yep
=> Fix link to table of contents

README.md
=> Add stylis.js

README.md
Fixes main readme grammar and generally cleans English blurbs.
yep!
=> Fixes main readme grammar

README.md
A utility-first CSS framework for rapid UI development.
Add tailwindcss in CSS Frameworks
Yes
=> Add tailwindcss in CSS Frameworks

README.md
This is a request to add eFrolic in CSS Framework.
It is a CSS framework, which without using javascript is interactive and animated. This framework is based on being simple and modern to develop web interfaces focused on mobile devices.
Yes.
=> Add eFrolic into CSS Framework

README.md
Adds an in-depth introduction to maintainability methodologies OOCSS, BEM, SMACSS to the Tutorials section. This article was written by a frontend designer friend of mine who's applied IRL these principles to his own development work.
Yes.
=> Add full intro to OOCSS/BEM/SMACSS to Tutorials

README.md
Add https://github.com/Heydon/REVENGE.CSS to MISC
Add https://github.com/Heydon/REVENGE.CSS to MISC
#160
=> Add https://github.com/Heydon/REVENGE.CSS

README.md
Added new CSS Framework to the list (Butter Cake) CSS framework.
Yes
=> Added Butter Cake CSS Framework

README.md
Update URL of string 129
> 
Yes
=> Update URL of string 129

README.md
Adds the Cirrus CSS framework to the README.
Yes
=> Add Cirrus CSS Framework

README.md
=> add CSS reset from Meyer

README.md
Added a link to video tutorial on Flexbox.
Yes
=> Flexbox video tutorial.

README.md
It will add Shorthand framework to Framework section
Yes
=> Added Shorthand framework

README.md
=> Add Gralig into README

README.md
Adds 'Bonsai' to 'Frameworks'
Yes
=> Add Bonsai to Frameworks

README.md
=> Adds a 2019 video

README.md
Added a new framework called Halfmoon: [https://www.gethalfmoon.com/](https://www.gethalfmoon.com/)
=> Added Halfmoon - Framework with dark mode

README.md
It adds Numl Design System to the framework list
Yes, (c) - absolutely unique in its approach and function
Numl is a unique Design System based on runtime CSS generation techniques.
=> add Numl Design System to Frameworks

README.md
It adds the the eBook Every Layout to the Book section.
Yes, it is both (b) discussed in the community due to it's innovative approach to the design problems faced when creating for multiple devices and screen sizes, and it is also (c) unique because it approaches CSS layout using algorithms instead of relying on breakpoints.
=> Add Every Layout to Books

README.md
=> added css podcast

README.md
Add xpath-to-selector to miscellaneous section.
Yes.
=> Add xpath-to-selector

README.md
Adds new CSS framework.
Yes. It's an absolutely unique in its approach and function, and a niche product that fills a gap.
Current charting solutions are all based on JS. This new open source framework does it with CSS.
=> Add Charts.css

README.md
Adds Reseter.css To The CSS Reset Collection
=> Add To CSS Resets

README.md
It adds a new CSS generator based on "glassmorphism" that is quite used and popular in the community:
https://ui.glass/generator/
https://www.producthunt.com/posts/glass-ui-generator
I've also added myself to the Twitter list, as I am actively writing about CSS and UI development. Currently building an open-source CSS UI library called Glass UI.
Yes, it does.
=> Added a CSS generator for glassmorphism

README.md
=> Update name references

README.md
I'm not sure, Please let me know if there are violations
=> Add Tronic247 Material

README.md
Add css-checker, a package to auto-detect similar CSS classes and reduce unused CSS styles
I suppose so.
=> add css-checker

README.md
=> Add Flexbox Patterns

README.md
Correct alphabetical order for all lists based on contribution guidelines
=> Correct alphabetical order

README.md
Adds AgnosticUI to the list of CSS frameworks
Yes, although disclaimer that I AM the creator of AgnosticUI so it is self-promotional.
=> Adds AgnosticUI

README.md
Hi,
Stjepan from Manning here. I thought this title might be a good match for your list. Thank you for considering it.
Best,
=> Added Tiny CSS Projects

README.md
Adds the useful ["Beautiful CSS box-shadow examples"](https://getcssscan.com/css-box-shadow-examples) resource under the "Miscellaneous" category.
Yes
=> Add Beautiful CSS box-shadow examples

README.md
Just added https://vanilla-extract.style/ to the preprocessor list
=> Added Vanilla Extract in Preprocessors list
